name: CI-dev

on:
  push:
    branches: [ dev-1.3.4 ]
  pull_request:
    branches: [ dev-1.3.4 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.4.0
    - name: Install Packages
      run: flutter packages get
    - name: Tests
      run: flutter test --no-pub --coverage
    - name: Ignore a file from coverage report
      run: flutter pub run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r 'momentum_router.old.dart'
    - name: Code Coverage -> Check
      uses: ChicagoFlutter/lcov-cop@v1.0.0
    - name: Code Coverage -> Upload
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
